name: "config-ssh"
description: "config-ssh"

runs:
  using: composite
  steps:
    - name: Setup ssh
      shell: bash
      run: |

        ## Enable ssh and login by password ##
        sudo chroot /mnt sh -c "sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config" || { echo "an error occured while setup ssh"; exit 1; }
        sudo chroot /mnt sh -c "systemctl enable ssh" || { echo "an error occured while starting ssh";exit 1; }

        ## Create required dirs and gen ssh-key ##
        sudo chroot /mnt mkdir -p /run/sshd
        sudo chroot /mnt chmod 0755 /run/sshd
        sudo chroot /mnt ssh-keygen -A

        ## Run ssh ##
        sudo chroot /mnt /usr/sbin/sshd -t|| { echo "an error occured while running ssh";exit 1; }
        sudo chroot /mnt touch /boot/firmware/ssh
