name: "zip-image"
description: "zip-image"
inputs:
  zip-image-path:
    type: string

runs:
  using: composite
  steps:
    - name: zip-image
      shell: bash
      run: |

        ## Unmount the image partition ##
        sudo umount /mnt

        ## Disconnect the image from nbd ##
        sudo qemu-nbd --disconnect /dev/nbd0

        ## Compress image ##
        xz raspios.img
