name: "plug-scripts"
description: "plug-scripts"

runs:
  using: composite
  steps:
    - name: prepare image
      shell: bash
      run: |

        if ! [ -e dronelibs.sh ]; then
          exit 1
        else 
          echo file exist
        fi

        sudo mv dronelibs.sh /mnt/usr/local/bin
        echo moved

        sudo chroot /mnt sudo chmod +x usr/local/bin/dronelibs.sh

        sudo sh -c "dronelibs.sh >> /mnt/etc/rc.local"
        sudo sh -c "echo 'exit 0' >> /mnt/etc/rc.local"
        cat /mnt/etc/rc.local
