name: "plug-scripts"
description: "plug-scripts"

runs:
  using: composite
  steps:
    - name: prepare image
      shell: bash
      run: |

        ## Give rights to rc.local
        sudo chroot /mnt chmod +x /etc/rc.local
        sudo chmod +x scripts/pluger.sh
        sudo cp -a scripts .
        sudo ls
        ## Plug script that installs py packages on boot
        scripts/pluger.sh dronelibs.sh usr/local/bin /mnt

        ## enable gpio/fix Error: Could not open port /dev/ttyS0
        ## Plug script that enables gpio after boot and reboot
        scripts/pluger.sh gpioenable.sh usr/local/bin /mnt
