name: "plug-scripts"
description: "plug-scripts"

runs:
  using: composite
  steps:
    - name: prepare image
      shell: bash
      run: |

        sudo chroot /mnt chmod +x /etc/rc.local

        ## plug script installing py packages
        sudo mv scripts/dronelibs.sh /mnt/usr/local/bin
        sudo chroot /mnt chmod +x /usr/local/bin/dronelibs.sh
        sudo chroot /mnt sh -c "sed -i 's|exit 0|dronelibs.sh|' /etc/rc.local"
        sudo chroot /mnt sh -c "echo exit 0 >> /etc/rc.local"

        ## enable gpio/uart
        sudo mv scripts/gpioenable.sh /mnt/usr/local/bin
        sudo chroot /mnt chmod +x /usr/local/bin/gpioenable.sh
        sudo chroot /mnt sh -c "sed -i 's|exit 0|gpioenable.sh|' /etc/rc.local"
        sudo chroot /mnt sh -c "echo exit 0 >> /etc/rc.local"
