name: "plug-scripts"
description: "plug-scripts"

runs:
  using: composite
  steps:
    - name: prepare image
      shell: bash
      run: |

        ## Check for instruments, create project with venv
        sudo mv dronelibs.sh /mnt/usr
        sudo chroot /mnt sh -c "sed -i 's|exit 0|/mnt/usr/dronelibs.sh|' /etc/rc.local"
        sudo echo exit 0 >> /mnt/etc/rc.local
        sudo chroot mnt chmod +x /etc/rc.local
        sudo chroot mnt chmod +x /usr/dronelibs.sh
