name: "plug-scripts"
description: "plug-scripts"

runs:
  using: composite
  steps:
    - name: prepare image
      shell: bash
      run: |

        ## Check for instruments, create project with venv
        python3 -V || { sudo chroot /mnt apt-get install -y python3; python3 -V; }
        pip3 -V || { sudo chroot /mnt apt-get install -y python3-pip; pip3 -V; }
        sudo chroot /mnt python -m venv /usr/drone 

        sudo chroot /mnt /usr/drone/bin/pip install pymavlink
        sudo chroot /mnt /usr/drone/bin/pip install dronekit
        sudo chroot /mnt /usr/drone/bin/pip install mavproxy
        echo "pkgs installed"
