name: "prepare-image"
description: "prepare-image"
inputs:
  zip-image-path:
    type: string

runs:
  using: composite
  steps:
    - name: Prepare image
      shell: bash
      run: |

        ## Get an image ##
          wget ${{ inputs.zip-image-path }}
          xz -d *img.xz
          mv *img raspios.img

        ## Install required packages ## 
        sudo apt-get update && sudo apt-get install -y qemu-utils qemu-user-static

        ## Load nbd kernel module ##
        sudo modprobe nbd max_part=8

        ## Connect the image to nbd ##
        sudo qemu-nbd --connect=/dev/nbd0 --format=raw raspios.img

        ## Install openssh-server on image ##
        sudo chroot /mnt sudo apt-get update && sudo apt-get install -y openssh-server
