name: "config-user"
description: "config-user"
inputs:
  username:
    required: true
    type: string
  password:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Create/change default user
      shell: bash
      run: |

        ## Initialize username and password variables ##
        USERNAME=${{ inputs.username }}
        PASSWORD=${{ inputs.password }}

        ## Delete $USERNAME with his directory /home/$USERNAME if exist ##
        sudo chroot /mnt sudo userdel -r $USERNAME || echo "user $USERNAME doesn't exist"

        ## Create $USERNAME with $PASSWORD password ##
        sudo chroot /mnt useradd -p $(echo $PASSWORD | openssl passwd -6 -stdin) -s /bin/bash -m $USERNAME || { echo "an error occured while creating $USERNAME"; exit 1; }
          
        ## Add $USERNAME to groups ##
        sudo chroot /mnt sudo usermod -aG sudo,adm,cdrom,users,input,render,gpio,i2c,spi $USERNAME || { echo "an error occured while adding user to groups"; exit 1; }

        ## userconf file test ##
        sudo sh -c "echo 'bedni:#(echo nodollars | openssl passwd -6 -stdin)' > /mnt/boot/firmware/userconf"
