name: "set-time-zone"
description: "set-time-zone"
inputs:
  time-zone:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: set-time-zone
      shell: bash
      run: |

        sudo chroot /mnt rm -rf /etc/localtime
        sudo chroot /mnt ln -sf /usr/share/zoneinfo/${{ inputs.time-zone }} /etc/localtime
        sudo chroot /mnt date
