name: "config-access-point"
description: "config-access-point"

runs:
  using: composite
  steps:
    - name: config-access-point
      shell: bash
      run: |

        sudo chroot /mnt sh -c "echo country=RU >> /etc/wpa_supplicant/wpa_supplicant.conf" 

        sudo chroot /mnt apt-get install -y hostapd dnsmasq

        unzip ap-cfgs
        sudo mv dnsmasq* /mnt/etc/dnsmasq.d
        sudo mv hostapd* /mnt/etc/hostapd
        sudo mv ifaces /mnt/etc/network/interfaces.d
        sudo sed -i 's|#DAEMON_CONF=""|DAEMON_CONF"/etc/hostapd/hostapd.conf"|' /mnt/etc/default/hostapd

        ## enable hostapd and dnsmasq on boot ## 
        sudo chroot /mnt sh -c "systemctl unmask hostapd" || { echo "an error occured while enabling hostapd";exit 1; }
        sudo chroot /mnt sh -c "systemctl enable hostapd" || { echo "an error occured while enabling hostapd";exit 1; }
        sudo chroot /mnt sh -c "systemctl enable dnsmasq" || { echo "an error occured while enabling dnsmasq";exit 1; }
