name: "config-access-point"
description: "config-access-point"

runs:
  using: composite
  steps:
    - name: config-access-point
      shell: bash
      run: |

        ## ? ##
        sudo chroot /mnt sudo sh -c "echo country=RU >> /etc/wpa_supplicant/wpa_supplicant.conf" 

        ## disable services working with network ##
        sudo chroot /mnt sudo sh -c "systemctl disable NetworkManager"
        sudo chroot /mnt sudo sh -c "systemctl stop NetworkManager" 

        sudo chroot /mnt sudo apt-get install -y hostapd dnsmasq

        unzip network-settings
        sudo mv dnsmasq /mnt/etc/dnsmasq.d
        sudo mv hostapd.conf /mnt/etc/hostapd
        sudo mv wlan0 /mnt/etc/network/interfaces.d
        sudo chroot /mnt sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1'

        ## setup the routing tables between wlan and ethernet ##
        sudo chroot /mnt sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
        sudo chroot /mnt sudo iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
        sudo chroot /mnt sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT

        ## save settings ##
        sudo chroot /mnt sh -c "iptables-save > /etc/iptables.ipv4.nat"

        sudo chroot /mnt ehco 'up iptables-restore < /etc/iptables.ipv4.nat' > /etc/network/interfaces.d/iptables

        sudo chroot /mnt sudo systemctl enable hostapd dnsmasq
