name: "config-access-point"
description: "config-access-point"

runs:
  using: composite
  steps:
    - name: config-access-point
      shell: bash
      run: |

        ## ? ##
        sudo chroot /mnt sudo sh -c "echo country=RU >> /etc/wpa_supplicant/wpa_supplicant.conf" 

        sudo chroot /mnt sudo apt-get install -y hostapd dnsmasq iptables

        ## disable services working with network ##
        sudo chroot /mnt sudo sh -c "systemctl disable NetworkManager"

        unzip network-settings
        sudo mv dnsmasq /mnt/etc/dnsmasq.d
        sudo mv hostapd.conf /mnt/etc/hostapd
        sudo mv wlan0 /mnt/etc/network/interfaces.d
        echo "delivery is done!"

        sudo chroot /mnt sudo sed -i 's|#net.ipv4.ip_forward=1|net.ipv4.ip_forward=1|' /etc/sysctl.conf

        ## setup the routing tables between wlan and ethernet ##
        sudo mv iptables.ipv4.nat /mnt/etc
        echo "iptables is setted"
        sudo touch /mnt/etc/network/interfaces.d/iptables
        sudo chroot echo 'up iptables-restore < /etc/iptables.ipv4.nat' > /mnt/etc/network/interfaces.d/iptables

        ## enable hostapd and dnsmasq on boot ## 
        sudo chroot /mnt sh -c "systemctl enable hostapd" || { echo "an error occured while enabling hostapd";exit 1; }
        sudo chroot /mnt sh -c "systemctl enable dnsmasq" || { echo "an error occured while enabling dnsmasq";exit 1; }
        echo "config-access-point is done"
