name: "test-image"
description: "test-image"

runs:
  using: composite
  steps:
    - name: test-image
      shell: bash
      run: |

        ## check for ssh file $##
        if [ -f /mnt/boot/firmware/ssh ]; then
          echo "Файл ssh найден"
        else
          echo "Файл ssh не найден" >&2
          exit 1
        fi

        ## check user list ##
        sudo chroot /mnt cat /etc/passwd
        sudo chroot /mnt cat /etc/hosts

        ## check sh service ##
        sudo chroot /mnt /usr/sbin/sshd -t || sudo chroot /mnt service ssh start
        sudo chroot /mnt /usr/sbin/sshd -t || {  echo "ssh service is not running"; exit 1; }

        ## Check for ip ##
        IP_ADDRESS=$(sudo chroot /mnt hostname -I | awk '{print $1}')
        if [ -n "$IP_ADDRESS" ]; then
          echo "Адрес: pi@$IP_ADDRESS"
        else
          echo "Не удалось получить IP-адрес" >&2
          exit 1
        fi
