name: Modify Raspberry Pi OS Image

on:
  push: # Запуск действия при каждом пуше в репозиторий
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: prepare-image
        uses: .github/workflows/prepare-image
        with:
          zip-image-path: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz

      - name: configure-image
        uses: .github/workflows/configure-image
        with:
          username: pi
          password: raspberry

      - name: test-image
        uses: .github/workflows/test-image

      - name: zip-image
        uses: .github/workflows/zip-image

      - name: deploy img.xz
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release'}}
        with:
          files: raspios.img.xz
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
