name: Modify Raspberry Pi OS Image

on:
  push: # Запуск действия при каждом пуше в репозиторий
    branches:
      - main
  release:
    types: [created]

jobs:
    modify-image:
        runs-on: ubuntu-latest # Использование последней версии Ubuntu для выполнения задач

        steps:
        - name: Checkout repository # Клонирование содержимого репозитория
          uses: actions/checkout@v3 # Использование действия для получения кода из репозитория

        # - name: Create copy of base image
        #   run: |
        #     sudo apt-get install xz-utils
        #     xz -dk *img.xz
        #     mv *img raspios.img

        - name: Spawn rpi image
          run: |
            wget https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
            xz -d *img.xz
            mv *img raspios.img

        - name: Install required packages # Установка необходимых утилит для работы с образом
          run: sudo apt-get update && sudo apt-get install -y qemu-utils qemu-user-static 

        - name: Load nbd kernel module # Загрузка модуля ядра nbd
          run: sudo modprobe nbd max_part=8

        - name: Connect the image to nbd # Подключение образа к nbd устройству
          run: sudo qemu-nbd --connect=/dev/nbd0 --format=raw raspios.img

        - name: Mount the image partition # Монтирование раздела образа
          run: sudo mount /dev/nbd0p2 /mnt

        # - name: Copy qemu tools to mounted image 
        #   run: |
        #     sudo cp /usr/bin/qemu-arm-static /mnt/usr/bin/
        #      if [ ! -f /usr/bin/qemu-arm-static ]; then
        #       echo "qemu-arm-static not found on host system!"
        #       exit 1
        #      fi
        #      sudo cp /usr/bin/qemu-arm-static /mnt/usr/bin/
        #      ls -l /mnt/usr/bin/qemu-arm-static
        #      if [ ! -f /mnt/usr/bin/qemu-arm-static ]; then
        #       echo "qemu-arm-static not found in the image!"
        #       exit 1
        #      fi
        #
        #  багает, иногда не может выполнить ls -l /mnt/usr/bin/qemu-arm-static: нет директории

        # - name: Install file manager in the image # Установка файлового менеджера в образ
        #   run: |
        #     sudo chroot /mnt apt-get update
        #     sudo chroot /mnt apt-get install -y mc

        # - name: Configurate image # Настройка образа 
        #   run: |
        #     sudo chroot /mnt raspi-config nonint do_wifi_ssid_passphrase myssid mypassphrase
        #     sudo chroot /mnt raspi-config nonint do_ssh 0
        #
        #   ошибка: fatal library error, lookup self
        #   System has not been booted with systemd as init system (PID 1). Can't operate. 

        - name: Setup ssh # подключение ssh и создание дефолтного пользователя. команда, использованная для шифрования пароля и вывода в консоль - echo 'raspberry' | openssl passwd -6 -stdin
                          # 'pi:encrypted_password'
          run: |
            sudo chroot /mnt sudo userdel pi
            sudo chroot /mnt sudo useradd -p $(perl -e 'print crypt($ARGV[0], "password")' raspberry) -s /bin/bash -G adm,cdrom,users,input,render,gpio,i2c,spi,sudo -m pi 
            sudo chroot /mnt sudo service ssh start
            sudo touch /mnt/boot/firmware/ssh

        #   echo 'pi:$6$4wZeqrrVWO9IPXdn$UjdB3q36d7AtE9AlW9xDarC05c6sXq1Vep470/Q6AOpATbhzsXqEDwo8tDNLORJNmXu5kmJb.wTalGBoEnpbU0' > userconf
        #   sudo cp userconf /mnt/boot/firmware/
        #   
        #   sudo systemctl enable ssh
            
        #   sudo rm /mnt/etc/systemd/system/multi-user.target.wants/userconfig.service
        #   sudo systemctl enable getty@tty1
        #
        #   не завершается запуск, встает на Finished systemd-update-utmp-runlevel.service - Record Runlevel Change in UTMP

        - name: Unmount the image partition # Демонтирование раздела образа
          run: sudo umount /mnt

        - name: Disconnect the image from nbd # Отключение образа от nbd устройства
          run: sudo qemu-nbd --disconnect /dev/nbd0

        - name: Compress image
          run: xz -k raspios.img

        - name: deploy img.xz
          uses: softprops/action-gh-release@v1
          if: ${{ github.event_name == 'release'}}
          with:
            files: raspios.img.xz
            prerelease: true
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}